apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.services.tasks.port }}
      targetPort: {{ .Values.services.tasks.port }}
