apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: users
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.services.users.port }}
      targetPort: {{ .Values.services.users.port }}